# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret)'
    backendType: 'azurerm'
    backendServiceArm: 'rbconn'
    backendAzureRmSubscriptionId: '47d57560-7ada-4bbf-9c81-c525f3c7410d'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'Rujhaan-RG'
    backendAzureRmResourceGroupLocation: 'EAST US'
    backendAzureRmStorageAccountName: 'rbtf1sa'
    backendAzureRmContainerName: 'tfrb'
    backendAzureRmKey: 'k8-rb12'
    allowTelemetryCollection: true
